-- ============================================================================
-- JDBC-ready Oracle 19c SQL for the passkey feature.
-- ACTIVE_PASSKEY retains the cooling window through which the current hash
-- became active. The two cooling columns are NULL for first registration.
-- ============================================================================

-- JQ01 - READ ACTIVE PASSKEY
-- Parameters: 1=CUST_ID. Expected result: 0 or 1 row.
SELECT CUST_ID, MOBILE_NUMBER, PASSKEY_HASH,
       COOLING_START_TIME, COOLING_END_TIME, UPDATED_TIME
FROM ACTIVE_PASSKEY
WHERE CUST_ID = ?;

-- JQ02 - READ PENDING PASSKEY
-- Parameters: 1=CUST_ID. Expected result: 0 or 1 row.
SELECT CUST_ID, MOBILE_NUMBER, PASSKEY_HASH,
       COOLING_START_TIME, COOLING_END_TIME
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- JQ03 - LOCK ACTIVE PASSKEY
-- Parameters: 1=CUST_ID. Expected result: 1 row when ACTIVE exists.
SELECT CUST_ID, MOBILE_NUMBER, PASSKEY_HASH,
       COOLING_START_TIME, COOLING_END_TIME, UPDATED_TIME
FROM ACTIVE_PASSKEY
WHERE CUST_ID = ?
FOR UPDATE;

-- JQ04 - LOCK PENDING PASSKEY
-- Lock only after JQ03.
-- Parameters: 1=CUST_ID. Expected result: 0 or 1 row.
SELECT CUST_ID, MOBILE_NUMBER, PASSKEY_HASH,
       COOLING_START_TIME, COOLING_END_TIME
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?
FOR UPDATE;

-- JQ05 - INSERT FIRST ACTIVE PASSKEY (Scenarios 2/3)
-- First registration has no cooling history, so both cooling values are NULL.
-- Parameters: 1=CUST_ID, 2=MOBILE_NUMBER, 3=PASSKEY_HASH.
-- Expected update count: 1.
INSERT INTO ACTIVE_PASSKEY
(CUST_ID, MOBILE_NUMBER, PASSKEY_HASH,
 COOLING_START_TIME, COOLING_END_TIME, UPDATED_TIME)
VALUES (?, ?, ?, NULL, NULL, SYSTIMESTAMP AT TIME ZONE 'UTC');

-- JQ06 - INSERT NEW PENDING PASSKEY (Scenarios 5/8/10)
-- Parameters: 1=CUST_ID, 2=PASSKEY_HASH, 3=MOBILE_NUMBER.
-- Expected update count: 1.
INSERT INTO PASSKEY_PENDING_VERIFICATION
(CUST_ID, PASSKEY_HASH, MOBILE_NUMBER, COOLING_START_TIME, COOLING_END_TIME)
SELECT ?, ?, ?, UTC_NOW, UTC_NOW + NUMTODSINTERVAL(48, 'HOUR')
FROM (
    SELECT SYSTIMESTAMP AT TIME ZONE 'UTC' AS UTC_NOW
    FROM DUAL
);

-- JQ07 - INSERT FOUR SMS SCHEDULE ROWS
-- Parameters: 1=CUST_ID. Expected update count: 4.
INSERT INTO PASSKEY_SMS_SCHEDULE
(CUST_ID, MOBILE_NUMBER, COOLING_START_TIME, SMS_SEQUENCE,
 SCHEDULED_TIME, NEXT_ATTEMPT_TIME, SMS_STATUS, CREATED_TIME, UPDATED_TIME)
SELECT P.CUST_ID,
       P.MOBILE_NUMBER,
       P.COOLING_START_TIME,
       S.SMS_SEQUENCE,
       CASE S.SMS_SEQUENCE
           WHEN 1 THEN P.COOLING_START_TIME
           WHEN 2 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(15, 'HOUR')
           WHEN 3 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(30, 'HOUR')
           WHEN 4 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(46, 'HOUR')
       END,
       CASE S.SMS_SEQUENCE
           WHEN 1 THEN P.COOLING_START_TIME
           WHEN 2 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(15, 'HOUR')
           WHEN 3 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(30, 'HOUR')
           WHEN 4 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(46, 'HOUR')
       END,
       'PENDING',
       SYSTIMESTAMP AT TIME ZONE 'UTC',
       SYSTIMESTAMP AT TIME ZONE 'UTC'
FROM PASSKEY_PENDING_VERIFICATION P
CROSS JOIN (
    SELECT 1 AS SMS_SEQUENCE FROM DUAL
    UNION ALL SELECT 2 FROM DUAL
    UNION ALL SELECT 3 FROM DUAL
    UNION ALL SELECT 4 FROM DUAL
) S
WHERE P.CUST_ID = ?;

-- JQ08 - ARCHIVE CURRENT PENDING PASSKEY
-- Parameters: 1=ARCHIVE_REASON, 2=CUST_ID. Expected update count: 1.
INSERT INTO PASSKEY_ARCHIVAL
(CUST_ID, PASSKEY_HASH, SOURCE_TYPE,
 ORIGINAL_COOLING_START_TIME, ORIGINAL_COOLING_END_TIME,
 ARCHIVE_REASON, ARCHIVED_TIME)
SELECT CUST_ID,
       PASSKEY_HASH,
       'PENDING_VERIFICATION',
       COOLING_START_TIME,
       COOLING_END_TIME,
       ?,
       SYSTIMESTAMP AT TIME ZONE 'UTC'
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- JQ09 - ARCHIVE CURRENT ACTIVE PASSKEY AS AR101
-- Copies the ACTIVE hash's own historical cooling window before replacement.
-- Parameters: 1=CUST_ID, 2=INCOMING_HASH. Expected update count: 1.
INSERT INTO PASSKEY_ARCHIVAL
(CUST_ID, PASSKEY_HASH, SOURCE_TYPE,
 ORIGINAL_UPDATED_TIME, ORIGINAL_COOLING_START_TIME,
 ORIGINAL_COOLING_END_TIME, ARCHIVE_REASON, ARCHIVED_TIME)
SELECT A.CUST_ID,
       A.PASSKEY_HASH,
       'ACTIVE',
       A.UPDATED_TIME,
       A.COOLING_START_TIME,
       A.COOLING_END_TIME,
       'AR101',
       SYSTIMESTAMP AT TIME ZONE 'UTC'
FROM ACTIVE_PASSKEY A
WHERE A.CUST_ID = ?
  AND EXISTS (
      SELECT 1
      FROM PASSKEY_PENDING_VERIFICATION P
      WHERE P.CUST_ID = A.CUST_ID
        AND P.PASSKEY_HASH = ?
        AND (SYSTIMESTAMP AT TIME ZONE 'UTC') >= P.COOLING_END_TIME
  );

-- JQ10 - PROMOTE PENDING HASH TO ACTIVE
-- Copies both cooling timestamps from PENDING to ACTIVE so activation history
-- remains available after the PENDING row is deleted.
-- Parameters: 1=INCOMING_HASH, 2=CUST_ID, 3=INCOMING_HASH.
-- Expected update count: 1.
UPDATE ACTIVE_PASSKEY A
SET (A.PASSKEY_HASH,
     A.MOBILE_NUMBER,
     A.COOLING_START_TIME,
     A.COOLING_END_TIME,
     A.UPDATED_TIME) =
    (
        SELECT P.PASSKEY_HASH,
               P.MOBILE_NUMBER,
               P.COOLING_START_TIME,
               P.COOLING_END_TIME,
               SYSTIMESTAMP AT TIME ZONE 'UTC'
        FROM PASSKEY_PENDING_VERIFICATION P
        WHERE P.CUST_ID = A.CUST_ID
          AND P.PASSKEY_HASH = ?
          AND (SYSTIMESTAMP AT TIME ZONE 'UTC') >= P.COOLING_END_TIME
    )
WHERE A.CUST_ID = ?
  AND EXISTS (
      SELECT 1
      FROM PASSKEY_PENDING_VERIFICATION P
      WHERE P.CUST_ID = A.CUST_ID
        AND P.PASSKEY_HASH = ?
        AND (SYSTIMESTAMP AT TIME ZONE 'UTC') >= P.COOLING_END_TIME
  );

-- JQ11 - CANCEL UNSENT SMS FOR ONE COOLING CYCLE
-- Parameters: 1=CANCEL_REASON, 2=CUST_ID, 3=COOLING_START_TIME.
-- Expected update count: 0..4.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'CANCELLED',
    CANCELLED_TIME = SYSTIMESTAMP AT TIME ZONE 'UTC',
    CANCEL_REASON = ?,
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP AT TIME ZONE 'UTC'
WHERE CUST_ID = ?
  AND COOLING_START_TIME = ?
  AND SMS_STATUS IN ('PENDING', 'QUEUED');

-- JQ12 - DELETE CURRENT PENDING ROW
-- Use exact cooling start to avoid deleting a replacement cycle accidentally.
-- Parameters: 1=CUST_ID, 2=COOLING_START_TIME. Expected update count: 1.
DELETE FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?
  AND COOLING_START_TIME = ?;

-- JQ13 - READ COOLING STATUS
-- Parameters: 1=CUST_ID. Expected result: 0 or 1 row.
SELECT CUST_ID,
       PASSKEY_HASH,
       MOBILE_NUMBER,
       COOLING_START_TIME,
       COOLING_END_TIME,
       CASE
           WHEN (SYSTIMESTAMP AT TIME ZONE 'UTC') < COOLING_END_TIME
               THEN 'ACTIVE'
           ELSE 'COMPLETED'
       END AS COOLING_STATUS
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- JDBC TRANSACTION FLOW -------------------------------------------------------
-- Scenarios 2/3: JQ01 -> JQ05 -> COMMIT.
-- Scenario 5: JQ03 -> JQ04(no pending) -> JQ06 -> JQ07 -> COMMIT.
-- Scenario 6: JQ03 -> JQ04(save cooling start) -> JQ08(AR102)
--             -> JQ11 -> JQ12 -> COMMIT.
-- Scenario 7: JQ01 + JQ13; no DML when same pending hash during cooling.
-- Scenario 8: JQ03 -> JQ04 -> JQ08(AR103) -> JQ11 -> JQ12
--             -> JQ06 -> JQ07 -> COMMIT.
-- Scenario 9: JQ03 -> JQ04 -> JQ09 -> JQ10 -> JQ11 -> JQ12 -> COMMIT.
--             JQ09 archives ACTIVE's previous cooling history; JQ10 copies the
--             promoted PENDING cooling history into ACTIVE.
-- Scenario 10: JQ03 -> JQ04 -> JQ08(AR104) -> JQ11 -> JQ12
--              -> JQ06 -> JQ07 -> COMMIT.
-- Any unexpected mandatory row count => ROLLBACK.
