-- ============================================================================
-- JDBC-ready Oracle 19c SQL for the passkey feature.
--
-- IMPORTANT JDBC NOTES
--   1. All bind parameters use positional '?' placeholders.
--   2. Parameter order is documented above every statement.
--   3. Hash comparison is still performed in Java, except Scenario 9 where SQL
--      also verifies the incoming hash before promotion as a defense-in-depth.
--   4. Use Connection#setAutoCommit(false) for state-changing scenarios.
--   5. Commit only after every statement in the scenario succeeds.
--   6. Roll back the complete transaction on any failure or unexpected row count.
--   7. ACTIVE row must be locked before PENDING row when both are required.
-- ============================================================================

-- ============================================================================
-- JQ01 - READ ACTIVE PASSKEY
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected result: zero or one row.
-- ============================================================================
SELECT CUST_ID,
       MOBILE_NUMBER,
       PASSKEY_HASH,
       UPDATED_TIME
FROM ACTIVE_PASSKEY
WHERE CUST_ID = ?;

-- ============================================================================
-- JQ02 - READ PENDING PASSKEY
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected result: zero or one row.
-- ============================================================================
SELECT CUST_ID,
       MOBILE_NUMBER,
       PASSKEY_HASH,
       COOLING_START_TIME,
       COOLING_END_TIME
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- ============================================================================
-- JQ03 - LOCK ACTIVE PASSKEY
-- Use before a transaction that may change ACTIVE/PENDING state.
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected result: one row when customer already has an ACTIVE passkey.
-- ============================================================================
SELECT CUST_ID,
       MOBILE_NUMBER,
       PASSKEY_HASH,
       UPDATED_TIME
FROM ACTIVE_PASSKEY
WHERE CUST_ID = ?
FOR UPDATE;

-- ============================================================================
-- JQ04 - LOCK PENDING PASSKEY
-- Always lock ACTIVE first, then PENDING, to keep lock order consistent.
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected result: zero or one row depending on current state.
-- ============================================================================
SELECT CUST_ID,
       MOBILE_NUMBER,
       PASSKEY_HASH,
       COOLING_START_TIME,
       COOLING_END_TIME
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?
FOR UPDATE;

-- ============================================================================
-- JQ05 - INSERT FIRST ACTIVE PASSKEY
-- Used by Scenarios 2 and 3 when no ACTIVE row exists.
-- JDBC parameters:
--   1 -> CUST_ID
--   2 -> MOBILE_NUMBER
--   3 -> PASSKEY_HASH
-- Expected update count: 1.
-- ============================================================================
INSERT INTO ACTIVE_PASSKEY
(
    CUST_ID,
    MOBILE_NUMBER,
    PASSKEY_HASH,
    UPDATED_TIME
)
VALUES
(
    ?,
    ?,
    ?,
    SYSTIMESTAMP AT TIME ZONE 'UTC'
);

-- ============================================================================
-- JQ06 - INSERT NEW PENDING PASSKEY
-- Used by Scenarios 5, 8 and 10.
-- COOLING_START_TIME is generated by Oracle; COOLING_END_TIME is exactly +48h.
-- JDBC parameters:
--   1 -> CUST_ID
--   2 -> PASSKEY_HASH
--   3 -> MOBILE_NUMBER
-- Expected update count: 1.
-- ============================================================================
INSERT INTO PASSKEY_PENDING_VERIFICATION
(
    CUST_ID,
    PASSKEY_HASH,
    MOBILE_NUMBER,
    COOLING_START_TIME,
    COOLING_END_TIME
)
SELECT ?,
       ?,
       ?,
       UTC_NOW,
       UTC_NOW + NUMTODSINTERVAL(48, 'HOUR')
FROM
(
    SELECT SYSTIMESTAMP AT TIME ZONE 'UTC' AS UTC_NOW
    FROM DUAL
);

-- ============================================================================
-- JQ07 - INSERT FOUR SMS SCHEDULE ROWS FOR CURRENT PENDING CYCLE
-- SMS 1 = immediate, SMS 2 = +15h, SMS 3 = +30h, SMS 4 = +46h.
-- SMS_SCHEDULE_ID is GENERATED ALWAYS AS IDENTITY, so JDBC does not supply it.
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected update count: 4.
-- ============================================================================
INSERT INTO PASSKEY_SMS_SCHEDULE
(
    CUST_ID,
    MOBILE_NUMBER,
    COOLING_START_TIME,
    SMS_SEQUENCE,
    SCHEDULED_TIME,
    NEXT_ATTEMPT_TIME,
    SMS_STATUS,
    CREATED_TIME,
    UPDATED_TIME
)
SELECT P.CUST_ID,
       P.MOBILE_NUMBER,
       P.COOLING_START_TIME,
       S.SMS_SEQUENCE,
       CASE S.SMS_SEQUENCE
           WHEN 1 THEN P.COOLING_START_TIME
           WHEN 2 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(15, 'HOUR')
           WHEN 3 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(30, 'HOUR')
           WHEN 4 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(46, 'HOUR')
       END,
       CASE S.SMS_SEQUENCE
           WHEN 1 THEN P.COOLING_START_TIME
           WHEN 2 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(15, 'HOUR')
           WHEN 3 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(30, 'HOUR')
           WHEN 4 THEN P.COOLING_START_TIME + NUMTODSINTERVAL(46, 'HOUR')
       END,
       'PENDING',
       SYSTIMESTAMP AT TIME ZONE 'UTC',
       SYSTIMESTAMP AT TIME ZONE 'UTC'
FROM PASSKEY_PENDING_VERIFICATION P
CROSS JOIN
(
    SELECT 1 AS SMS_SEQUENCE FROM DUAL
    UNION ALL SELECT 2 FROM DUAL
    UNION ALL SELECT 3 FROM DUAL
    UNION ALL SELECT 4 FROM DUAL
) S
WHERE P.CUST_ID = ?;

-- ============================================================================
-- JQ08 - ARCHIVE CURRENT PENDING PASSKEY
-- Used by Scenarios 6, 8 and 10.
-- Valid archive reason values for PENDING source:
--   AR102 = original ACTIVE hash reconfirmed
--   AR103 = pending hash replaced during cooling
--   AR104 = pending hash replaced after cooling
-- ARCHIVAL_ID is GENERATED ALWAYS AS IDENTITY.
-- JDBC parameters:
--   1 -> ARCHIVE_REASON (AR102 / AR103 / AR104)
--   2 -> CUST_ID
-- Expected update count: 1.
-- ============================================================================
INSERT INTO PASSKEY_ARCHIVAL
(
    CUST_ID,
    PASSKEY_HASH,
    SOURCE_TYPE,
    ORIGINAL_COOLING_START_TIME,
    ORIGINAL_COOLING_END_TIME,
    ARCHIVE_REASON,
    ARCHIVED_TIME
)
SELECT CUST_ID,
       PASSKEY_HASH,
       'PENDING_VERIFICATION',
       COOLING_START_TIME,
       COOLING_END_TIME,
       ?,
       SYSTIMESTAMP AT TIME ZONE 'UTC'
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- ============================================================================
-- JQ09 - ARCHIVE CURRENT ACTIVE PASSKEY (AR101)
-- Used only by Scenario 9 immediately before replacing ACTIVE with PENDING.
-- Defense-in-depth: archive happens only when incoming hash matches PENDING and
-- cooling period is already complete.
-- JDBC parameters:
--   1 -> INCOMING_HASH
--   2 -> CUST_ID
-- Expected update count: 1.
-- ============================================================================
INSERT INTO PASSKEY_ARCHIVAL
(
    CUST_ID,
    PASSKEY_HASH,
    SOURCE_TYPE,
    ORIGINAL_UPDATED_TIME,
    ARCHIVE_REASON,
    ARCHIVED_TIME
)
SELECT A.CUST_ID,
       A.PASSKEY_HASH,
       'ACTIVE',
       A.UPDATED_TIME,
       'AR101',
       SYSTIMESTAMP AT TIME ZONE 'UTC'
FROM ACTIVE_PASSKEY A
WHERE A.CUST_ID = ?
  AND EXISTS
      (
          SELECT 1
          FROM PASSKEY_PENDING_VERIFICATION P
          WHERE P.CUST_ID = A.CUST_ID
            AND P.PASSKEY_HASH = ?
            AND (SYSTIMESTAMP AT TIME ZONE 'UTC') >= P.COOLING_END_TIME
      );
-- NOTE: PreparedStatement parameter order for this SQL is:
--   1 -> CUST_ID
--   2 -> INCOMING_HASH

-- ============================================================================
-- JQ10 - PROMOTE PENDING HASH TO ACTIVE
-- Used by Scenario 9 after JQ09 succeeds.
-- SQL independently verifies incoming hash and completed cooling period.
-- JDBC parameters:
--   1 -> INCOMING_HASH
--   2 -> CUST_ID
-- Expected update count: 1. Any other count must roll back the transaction.
-- ============================================================================
UPDATE ACTIVE_PASSKEY A
SET (A.PASSKEY_HASH, A.MOBILE_NUMBER, A.UPDATED_TIME) =
    (
        SELECT P.PASSKEY_HASH,
               P.MOBILE_NUMBER,
               SYSTIMESTAMP AT TIME ZONE 'UTC'
        FROM PASSKEY_PENDING_VERIFICATION P
        WHERE P.CUST_ID = A.CUST_ID
          AND P.PASSKEY_HASH = ?
          AND (SYSTIMESTAMP AT TIME ZONE 'UTC') >= P.COOLING_END_TIME
    )
WHERE A.CUST_ID = ?
  AND EXISTS
      (
          SELECT 1
          FROM PASSKEY_PENDING_VERIFICATION P
          WHERE P.CUST_ID = A.CUST_ID
            AND P.PASSKEY_HASH = ?
            AND (SYSTIMESTAMP AT TIME ZONE 'UTC') >= P.COOLING_END_TIME
      );
-- PreparedStatement parameter order:
--   1 -> INCOMING_HASH
--   2 -> CUST_ID
--   3 -> INCOMING_HASH

-- ============================================================================
-- JQ11 - CANCEL UNSENT SMS FOR ONE COOLING CYCLE
-- Used when PENDING is cancelled/replaced/promoted.
-- SENT rows remain intact. PROCESSING rows require provider-aware handling.
-- JDBC parameters:
--   1 -> CANCEL_REASON
--   2 -> CUST_ID
--   3 -> COOLING_START_TIME (value read from locked PENDING row)
-- Expected update count: 0..4 depending on how many SMS were already sent.
-- ============================================================================
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'CANCELLED',
    CANCELLED_TIME = SYSTIMESTAMP AT TIME ZONE 'UTC',
    CANCEL_REASON = ?,
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP AT TIME ZONE 'UTC'
WHERE CUST_ID = ?
  AND COOLING_START_TIME = ?
  AND SMS_STATUS IN ('PENDING', 'QUEUED');

-- ============================================================================
-- JQ12 - DELETE CURRENT PENDING ROW
-- Execute only after archival/SMS cancellation/promotion work is complete.
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected update count: 1 for Scenarios 6, 8, 9 and 10.
-- ============================================================================
DELETE FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- ============================================================================
-- JQ13 - READ COOLING STATUS
-- Used by Scenarios 7, 9 and 10.
-- JDBC parameters:
--   1 -> CUST_ID
-- Expected result: zero or one row.
-- ============================================================================
SELECT CUST_ID,
       PASSKEY_HASH,
       MOBILE_NUMBER,
       COOLING_START_TIME,
       COOLING_END_TIME,
       CASE
           WHEN (SYSTIMESTAMP AT TIME ZONE 'UTC') < COOLING_END_TIME
               THEN 'ACTIVE'
           ELSE 'COMPLETED'
       END AS COOLING_STATUS
FROM PASSKEY_PENDING_VERIFICATION
WHERE CUST_ID = ?;

-- ============================================================================
-- JDBC TRANSACTION FLOW BY BUSINESS SCENARIO
-- ============================================================================
-- Scenario 1:
--   No SQL.
--
-- Scenarios 2/3:
--   JQ01 -> if no row, JQ05 -> COMMIT.
--
-- Scenario 4:
--   JQ01 -> compare incomingHash with ACTIVE in Java.
--   JQ02 -> if no pending, no DML. If pending exists, execute Scenario 6 flow.
--
-- Scenario 5 (first mismatch):
--   BEGIN TX
--   JQ03 (lock ACTIVE)
--   JQ04 (confirm no PENDING)
--   JQ06 (insert PENDING, expect 1)
--   JQ07 (insert four SMS rows, expect 4)
--   COMMIT
--
-- Scenario 6 (ACTIVE hash used while PENDING exists):
--   BEGIN TX
--   JQ03 (lock ACTIVE)
--   JQ04 (lock PENDING; save COOLING_START_TIME)
--   JQ08 with AR102 (expect 1)
--   JQ11 cancel remaining SMS
--   JQ12 delete PENDING (expect 1)
--   COMMIT
--
-- Scenario 7 (same PENDING hash during cooling):
--   JQ01 + JQ13. If incomingHash matches PENDING and cooling=ACTIVE, no DML.
--
-- Scenario 8 (different hash during cooling):
--   BEGIN TX
--   JQ03
--   JQ04 (save old COOLING_START_TIME)
--   JQ08 with AR103 (expect 1)
--   JQ11 cancel old SMS
--   JQ12 delete old PENDING (expect 1)
--   JQ06 insert new PENDING (expect 1)
--   JQ07 create new four SMS rows (expect 4)
--   COMMIT
--
-- Scenario 9 (matching PENDING hash after cooling):
--   BEGIN TX
--   JQ03
--   JQ04 (save COOLING_START_TIME; verify hash/cooling in Java)
--   JQ09 archive ACTIVE using SQL guard (expect 1)
--   JQ10 promote PENDING using SQL guard (expect 1)
--   JQ11 cancel any remaining SMS
--   JQ12 delete PENDING (expect 1)
--   COMMIT
--
-- Scenario 10 (different hash after cooling):
--   BEGIN TX
--   JQ03
--   JQ04 (save old COOLING_START_TIME)
--   JQ08 with AR104 (expect 1)
--   JQ11 cancel old SMS
--   JQ12 delete old PENDING (expect 1)
--   JQ06 insert new PENDING (expect 1)
--   JQ07 create four SMS rows (expect 4)
--   COMMIT
--
-- For all state-changing flows: if any expected row count is violated, ROLLBACK.
