-- Support and audit queries. Avoid exposing full passkey hashes in UIs or logs.

-- Current state for a customer.
SELECT A.CUST_NUMBER,
       A.PASSKEY_HASH AS ACTIVE_HASH,
       A.ACTIVATED_TIME,
       P.VERIFICATION_CYCLE_ID,
       P.PASSKEY_HASH AS PENDING_HASH,
       P.COOLING_START_TIME,
       P.COOLING_END_TIME,
       CASE
           WHEN P.COOLING_END_TIME IS NULL THEN 'NOT_APPLICABLE'
           WHEN SYSTIMESTAMP < P.COOLING_END_TIME THEN 'ACTIVE'
           ELSE 'COMPLETED'
       END AS COOLING_STATUS
FROM ACTIVE_PASSKEY A
LEFT JOIN PASSKEY_PENDING_VERIFICATION P
  ON P.CUST_NUMBER = A.CUST_NUMBER
WHERE A.CUST_NUMBER = :custNumber;

-- Passkey archive history.
SELECT ARCHIVAL_ID, CUST_NUMBER, SOURCE_TYPE, VERIFICATION_CYCLE_ID,
       ORIGINAL_REQUEST_ID, ORIGINAL_ACTIVATED_TIME,
       ORIGINAL_COOLING_START_TIME, ORIGINAL_COOLING_END_TIME,
       ARCHIVE_REASON, ARCHIVED_REQUEST_ID, ARCHIVED_TIME
FROM PASSKEY_ARCHIVAL
WHERE CUST_NUMBER = :custNumber
ORDER BY ARCHIVED_TIME DESC;

-- SMS delivery history.
SELECT SMS_SCHEDULE_ID, VERIFICATION_CYCLE_ID, SMS_SEQUENCE,
       SCHEDULED_TIME, NEXT_ATTEMPT_TIME, SMS_STATUS,
       ATTEMPT_COUNT, SENT_TIME, CANCELLED_TIME, CANCEL_REASON
FROM PASSKEY_SMS_SCHEDULE
WHERE CUST_NUMBER = :custNumber
ORDER BY CREATED_TIME DESC, SMS_SEQUENCE;

-- Pending cycles whose cooling period is complete.
SELECT VERIFICATION_CYCLE_ID, CUST_NUMBER,
       COOLING_START_TIME, COOLING_END_TIME
FROM PASSKEY_PENDING_VERIFICATION
WHERE SYSTIMESTAMP >= COOLING_END_TIME
ORDER BY COOLING_END_TIME;

-- Scheduler backlog summary.
SELECT SMS_STATUS, COUNT(*) AS RECORD_COUNT,
       MIN(NVL(NEXT_ATTEMPT_TIME, SCHEDULED_TIME)) AS EARLIEST_DUE_TIME
FROM PASSKEY_SMS_SCHEDULE
GROUP BY SMS_STATUS
ORDER BY SMS_STATUS;

-- Overdue pending SMS rows.
SELECT SMS_SCHEDULE_ID, VERIFICATION_CYCLE_ID, CUST_NUMBER,
       SMS_SEQUENCE, SCHEDULED_TIME, NEXT_ATTEMPT_TIME, ATTEMPT_COUNT
FROM PASSKEY_SMS_SCHEDULE
WHERE SMS_STATUS = 'PENDING'
  AND NVL(NEXT_ATTEMPT_TIME, SCHEDULED_TIME) < SYSTIMESTAMP
ORDER BY NVL(NEXT_ATTEMPT_TIME, SCHEDULED_TIME);
