-- Oracle 19c schema for passkey verification and SMS scheduling.

CREATE SEQUENCE SEQ_PASSKEY_VERIFICATION_CYCLE
    START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE;

CREATE SEQUENCE SEQ_PASSKEY_ARCHIVAL
    START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE;

CREATE SEQUENCE SEQ_PASSKEY_SMS_SCHEDULE
    START WITH 1 INCREMENT BY 1 CACHE 100 NOCYCLE;

CREATE TABLE ACTIVE_PASSKEY
(
    CUST_NUMBER             VARCHAR2(20 CHAR) NOT NULL,
    PASSKEY_HASH            VARCHAR2(150 CHAR) NOT NULL,
    ACTIVATED_TIME          TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    ACTIVATION_REQUEST_ID   VARCHAR2(100 CHAR) NOT NULL,
    CREATED_TIME            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIME            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION_NO              NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ACTIVE_PASSKEY PRIMARY KEY (CUST_NUMBER)
);

CREATE TABLE PASSKEY_PENDING_VERIFICATION
(
    VERIFICATION_CYCLE_ID   NUMBER NOT NULL,
    CUST_NUMBER             VARCHAR2(20 CHAR) NOT NULL,
    PASSKEY_HASH            VARCHAR2(150 CHAR) NOT NULL,
    COOLING_START_TIME      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COOLING_END_TIME        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_REQUEST_ID      VARCHAR2(100 CHAR) NOT NULL,
    CREATED_TIME            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIME            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION_NO              NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PENDING_VERIFICATION PRIMARY KEY (VERIFICATION_CYCLE_ID),
    CONSTRAINT UK_PENDING_CUST_NUMBER UNIQUE (CUST_NUMBER),
    CONSTRAINT CK_PENDING_COOLING_TIME CHECK (COOLING_END_TIME > COOLING_START_TIME)
);

CREATE TABLE PASSKEY_ARCHIVAL
(
    ARCHIVAL_ID                 NUMBER NOT NULL,
    CUST_NUMBER                 VARCHAR2(20 CHAR) NOT NULL,
    PASSKEY_HASH                VARCHAR2(150 CHAR) NOT NULL,
    SOURCE_TYPE                 VARCHAR2(30 CHAR) NOT NULL,
    VERIFICATION_CYCLE_ID       NUMBER,
    ORIGINAL_REQUEST_ID         VARCHAR2(100 CHAR),
    ORIGINAL_CREATED_TIME       TIMESTAMP(6) WITH TIME ZONE,
    ORIGINAL_ACTIVATED_TIME     TIMESTAMP(6) WITH TIME ZONE,
    ORIGINAL_COOLING_START_TIME TIMESTAMP(6) WITH TIME ZONE,
    ORIGINAL_COOLING_END_TIME   TIMESTAMP(6) WITH TIME ZONE,
    ARCHIVE_REASON              VARCHAR2(60 CHAR) NOT NULL,
    ARCHIVED_REQUEST_ID         VARCHAR2(100 CHAR),
    ARCHIVED_TIME               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PASSKEY_ARCHIVAL PRIMARY KEY (ARCHIVAL_ID),
    CONSTRAINT CK_ARCHIVAL_SOURCE_TYPE CHECK
        (SOURCE_TYPE IN ('ACTIVE', 'PENDING_VERIFICATION')),
    CONSTRAINT CK_PASSKEY_ARCHIVE_REASON CHECK
        (ARCHIVE_REASON IN
        ('ACTIVE_REPLACED_AFTER_COOLING',
         'ACTIVE_HASH_RECONFIRMED',
         'PENDING_REPLACED_DURING_COOLING',
         'PENDING_REPLACED_AFTER_COOLING'))
);

CREATE TABLE PASSKEY_SMS_SCHEDULE
(
    SMS_SCHEDULE_ID         NUMBER NOT NULL,
    VERIFICATION_CYCLE_ID   NUMBER NOT NULL,
    CUST_NUMBER             VARCHAR2(20 CHAR) NOT NULL,
    SMS_SEQUENCE            NUMBER(1) NOT NULL,
    SCHEDULED_TIME          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    NEXT_ATTEMPT_TIME       TIMESTAMP(6) WITH TIME ZONE,
    SMS_STATUS              VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    QUEUED_TIME             TIMESTAMP(6) WITH TIME ZONE,
    PROCESSING_START_TIME   TIMESTAMP(6) WITH TIME ZONE,
    SENT_TIME               TIMESTAMP(6) WITH TIME ZONE,
    CANCELLED_TIME          TIMESTAMP(6) WITH TIME ZONE,
    CANCEL_REASON           VARCHAR2(60 CHAR),
    ATTEMPT_COUNT           NUMBER DEFAULT 0 NOT NULL,
    LAST_ERROR_MESSAGE      VARCHAR2(1000 CHAR),
    LOCKED_BY               VARCHAR2(100 CHAR),
    LOCKED_TIME             TIMESTAMP(6) WITH TIME ZONE,
    CREATED_TIME            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_TIME            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PASSKEY_SMS_SCHEDULE PRIMARY KEY (SMS_SCHEDULE_ID),
    CONSTRAINT UK_SMS_CYCLE_SEQUENCE UNIQUE (VERIFICATION_CYCLE_ID, SMS_SEQUENCE),
    CONSTRAINT CK_SMS_SEQUENCE CHECK (SMS_SEQUENCE IN (1, 2, 3, 4)),
    CONSTRAINT CK_SMS_STATUS CHECK
        (SMS_STATUS IN ('PENDING','QUEUED','PROCESSING','SENT','CANCELLED','FAILED'))
);

CREATE INDEX IDX_PENDING_CUSTOMER_COOLING
    ON PASSKEY_PENDING_VERIFICATION (CUST_NUMBER, COOLING_END_TIME);

CREATE INDEX IDX_ARCHIVAL_CUSTOMER_TIME
    ON PASSKEY_ARCHIVAL (CUST_NUMBER, ARCHIVED_TIME);

CREATE INDEX IDX_SMS_STATUS_SCHEDULE_TIME
    ON PASSKEY_SMS_SCHEDULE (SMS_STATUS, SCHEDULED_TIME);

CREATE INDEX IDX_SMS_CYCLE_STATUS
    ON PASSKEY_SMS_SCHEDULE (VERIFICATION_CYCLE_ID, SMS_STATUS);

CREATE INDEX IDX_SMS_CUSTOMER_TIME
    ON PASSKEY_SMS_SCHEDULE (CUST_NUMBER, CREATED_TIME);

CREATE INDEX IDX_SMS_NEXT_ATTEMPT
    ON PASSKEY_SMS_SCHEDULE (SMS_STATUS, NEXT_ATTEMPT_TIME);
