-- Oracle 19c SQL used by the Java database scanner and DelayQueue workers.
-- The database is the source of truth; DelayQueue is only an in-memory timer.

-- 1. Claim records due within a configurable look-ahead window.
SELECT SMS_SCHEDULE_ID, VERIFICATION_CYCLE_ID, CUST_NUMBER,
       SMS_SEQUENCE, SCHEDULED_TIME, NEXT_ATTEMPT_TIME, ATTEMPT_COUNT
FROM PASSKEY_SMS_SCHEDULE
WHERE SMS_STATUS = 'PENDING'
  AND NVL(NEXT_ATTEMPT_TIME, SCHEDULED_TIME)
      <= SYSTIMESTAMP + NUMTODSINTERVAL(:lookAheadMinutes, 'MINUTE')
ORDER BY NVL(NEXT_ATTEMPT_TIME, SCHEDULED_TIME)
FOR UPDATE SKIP LOCKED;

-- 2. Mark claimed row as queued. Add to DelayQueue only when row count is 1.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'QUEUED',
    QUEUED_TIME = SYSTIMESTAMP,
    LOCKED_BY = :schedulerInstanceId,
    LOCKED_TIME = SYSTIMESTAMP,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_SCHEDULE_ID = :smsScheduleId
  AND SMS_STATUS = 'PENDING';

-- 3. Revalidate the pending cycle before sending.
SELECT S.SMS_STATUS,
       S.SCHEDULED_TIME,
       S.NEXT_ATTEMPT_TIME,
       CASE WHEN P.VERIFICATION_CYCLE_ID IS NOT NULL THEN 'Y' ELSE 'N' END
           AS PENDING_CYCLE_ACTIVE
FROM PASSKEY_SMS_SCHEDULE S
LEFT JOIN PASSKEY_PENDING_VERIFICATION P
  ON P.VERIFICATION_CYCLE_ID = S.VERIFICATION_CYCLE_ID
WHERE S.SMS_SCHEDULE_ID = :smsScheduleId;
-- Send only when SMS_STATUS='QUEUED' and PENDING_CYCLE_ACTIVE='Y'.

-- 4. Atomically transition to processing. Send only when row count is 1.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'PROCESSING',
    PROCESSING_START_TIME = SYSTIMESTAMP,
    ATTEMPT_COUNT = ATTEMPT_COUNT + 1,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_SCHEDULE_ID = :smsScheduleId
  AND SMS_STATUS = 'QUEUED';

-- 5. Successful delivery.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'SENT',
    SENT_TIME = SYSTIMESTAMP,
    NEXT_ATTEMPT_TIME = NULL,
    LAST_ERROR_MESSAGE = NULL,
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_SCHEDULE_ID = :smsScheduleId
  AND SMS_STATUS = 'PROCESSING';

-- 6. Retryable failure. Example retry delay: five minutes.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'PENDING',
    NEXT_ATTEMPT_TIME = SYSTIMESTAMP + NUMTODSINTERVAL(:retryDelayMinutes, 'MINUTE'),
    LAST_ERROR_MESSAGE = :maskedErrorMessage,
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_SCHEDULE_ID = :smsScheduleId
  AND SMS_STATUS = 'PROCESSING';

-- 7. Permanent failure after maximum retry count.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'FAILED',
    NEXT_ATTEMPT_TIME = NULL,
    LAST_ERROR_MESSAGE = :maskedErrorMessage,
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_SCHEDULE_ID = :smsScheduleId
  AND SMS_STATUS = 'PROCESSING';

-- 8. Recover stranded QUEUED records after JVM termination.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'PENDING',
    QUEUED_TIME = NULL,
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_STATUS = 'QUEUED'
  AND LOCKED_TIME < SYSTIMESTAMP - NUMTODSINTERVAL(:leaseMinutes, 'MINUTE');

-- 9. Recover stranded PROCESSING records.
-- Provider-side idempotency is recommended to prevent duplicate SMS delivery.
UPDATE PASSKEY_SMS_SCHEDULE
SET SMS_STATUS = 'PENDING',
    PROCESSING_START_TIME = NULL,
    NEXT_ATTEMPT_TIME = SYSTIMESTAMP + NUMTODSINTERVAL(:retryDelayMinutes, 'MINUTE'),
    LAST_ERROR_MESSAGE = 'Recovered after processing lease expiration',
    LOCKED_BY = NULL,
    LOCKED_TIME = NULL,
    UPDATED_TIME = SYSTIMESTAMP
WHERE SMS_STATUS = 'PROCESSING'
  AND PROCESSING_START_TIME
      < SYSTIMESTAMP - NUMTODSINTERVAL(:leaseMinutes, 'MINUTE');
